### ISSUE TITLE
Clarification about the `-d` flag

### ISSUE THREAD

**Issue by aadcg** [Ambrevar/lisp-repl-core-dumper#1]
@Ambrevar thank you for this amazing tool!

I'm wondering if the explanation below wouldn't make more sense, since I don't think you can say:
```lisp-repl-core-dumper -d nfiles history-tree sbcl```

Rather, you need to say:
```lisp-repl-core-dumper -d nfiles -d history-tree sbcl```

```diff
-  -d SYSTEMS: Preload the systems that SYSTEMS depend on.
-              This is useful to build an environment to work on SYSTEMS themselves.
-              Can be specified multiple times.
+  -d SYSTEM: Preload the systems that SYSTEM depends on.
+             This is useful to build an environment to work on SYSTEM itself.
+             Can be specified multiple times.
```

Does that make sense?

**Comment by Ambrevar** [comment]
Right, actually `-d` and `-s` follow the same syntax: both can be specified multiple times and their argument can be a string of space-separated systems.

Mind sending a patch?

**Comment by aadcg** [comment]
@Ambrevar this repository also exists on GitLab and, judging by the Guix's package definition, the GitLab instance might be the "official" one. Would you prefer if I send the patch to GitLab?

**Comment by Ambrevar** [comment]
Yes please, the GitHub repo is a mirror.

**Comment by aadcg** [comment]
See https://gitlab.com/ambrevar/lisp-repl-core-dumper/-/merge_requests/2.

Thanks!
